imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: ru

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# Third party
assetic:
    bundles: [ AppBundle ]
    filters:
        closure:
            jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        cssembed:
            jar: "%kernel.root_dir%/Resources/java/cssembed-0.4.5.jar"
        cssrewrite: ~
        yui_css:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.8.jar"

easy_admin:
    design:
        form_theme: [ horizontal, VichUploaderBundle:Form:fields.html.twig ]
    entities:
        Penguin:
            class: AppBundle\Entity\Penguin
            form:
                fields:
                    - { property: title,     type: text }
                    - { property: imageFile, type: vich_image }
        User:
            class: AppBundle\Entity\User

fos_user:
    db_driver:     orm
    firewall_name: admin
    user_class:    AppBundle\Entity\User

liip_imagine:
    filter_sets:
        penguin_thumb:
            quality: 75
            filters:
                thumbnail:
                    size: [ 1024, 768 ]
                    mode: outbound
                watermark:
                    image:    Resources/images/watermark.png
                    size:     0.3
                    position: bottomleft

vich_uploader:
    db_driver: orm
    mappings:
        penguin_image:
            uri_prefix:         /images/penguins
            upload_destination: "%kernel.root_dir%/../web/images/penguins"

# App
app:
    homepage_penguins: "%homepage_penguins%"
