# Third party
easy_admin:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

# App
app:
    resource: "@AppBundle/Resources/config/routing.yml"
